export const COLLEGES = [
  "Amrita Vishwa Vidyapeetham, Bengaluru",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Anna University, Chennai",
  "BMS College of Engineering, Bengaluru",
  "CBIT, Hyderabad",
  "College of Engineering, Pune",
  "Delhi Technological University",
  "GITAM University, Visakhapatnam",
  "JNTU Hyderabad",
  "JNTU Kakinada",
  "KL University, Vijayawada",
  "Lovely Professional University",
  "Manipal Institute of Technology",
  "NIT Trichy",
  "NIT Warangal",
  "PSG College of Technology, Coimbatore",
  "R.V. College of Engineering, Bengaluru",
  "SRM Institute of Science and Technology",
  "VIT Vellore",
  "VNR VJIET, Hyderabad",
];
